# Site settings
author: Sergio Marelli
title: Sergio Sharing
header-img: img/home-bg.png
email: sergio.mrll@gmail.com
copyright_name: Sergio Marelli
description: > # this means to ignore newlines until "baseurl:"
  Design looking for Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  AskBid

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
